//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentGradeManager.CourseServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourseServiceReference.ICourseService")]
    public interface ICourseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SaveCourse", ReplyAction="http://tempuri.org/ICourseService/SaveCourseResponse")]
        int SaveCourse(StudentDataModel.Course c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/SaveCourse", ReplyAction="http://tempuri.org/ICourseService/SaveCourseResponse")]
        System.Threading.Tasks.Task<int> SaveCourseAsync(StudentDataModel.Course c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetData", ReplyAction="http://tempuri.org/ICourseService/GetDataResponse")]
        StudentDataModel.Course[] GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetData", ReplyAction="http://tempuri.org/ICourseService/GetDataResponse")]
        System.Threading.Tasks.Task<StudentDataModel.Course[]> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseServiceChannel : StudentGradeManager.CourseServiceReference.ICourseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseServiceClient : System.ServiceModel.ClientBase<StudentGradeManager.CourseServiceReference.ICourseService>, StudentGradeManager.CourseServiceReference.ICourseService {
        
        public CourseServiceClient() {
        }
        
        public CourseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveCourse(StudentDataModel.Course c) {
            return base.Channel.SaveCourse(c);
        }
        
        public System.Threading.Tasks.Task<int> SaveCourseAsync(StudentDataModel.Course c) {
            return base.Channel.SaveCourseAsync(c);
        }
        
        public StudentDataModel.Course[] GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<StudentDataModel.Course[]> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
