//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseModule()
        {
            this.ModuleAssessment = new HashSet<ModuleAssessment>();
        }
    
        public System.Guid CourseModuleID { get; set; }
        public System.Guid CourseID { get; set; }
        public string CourseModuleTitle { get; set; }
        public string CourseModuleCode { get; set; }
        public string CourseModuleDescription { get; set; }
        public int ModuleType { get; set; }
        public int Level { get; set; }
        public Nullable<bool> ContributedToFinal { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Expired { get; set; }
        public double CourseModuleCreditValue { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleAssessment> ModuleAssessment { get; set; }
    }
}
