//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentGradeManager.ModuleAssessmentServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModuleAssessmentServiceReference.IModuleAssessmentService")]
    public interface IModuleAssessmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAssessmentService/DoWork", ReplyAction="http://tempuri.org/IModuleAssessmentService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAssessmentService/DoWork", ReplyAction="http://tempuri.org/IModuleAssessmentService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModuleAssessmentServiceChannel : StudentGradeManager.ModuleAssessmentServiceReference.IModuleAssessmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModuleAssessmentServiceClient : System.ServiceModel.ClientBase<StudentGradeManager.ModuleAssessmentServiceReference.IModuleAssessmentService>, StudentGradeManager.ModuleAssessmentServiceReference.IModuleAssessmentService {
        
        public ModuleAssessmentServiceClient() {
        }
        
        public ModuleAssessmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModuleAssessmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuleAssessmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuleAssessmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
