//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentGradeManager.ModuleAssessmentServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModuleAssessmentServiceReference.IModuleAssessmentService")]
    public interface IModuleAssessmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAssessmentService/SaveAssessment", ReplyAction="http://tempuri.org/IModuleAssessmentService/SaveAssessmentResponse")]
        int SaveAssessment(StudentDataModel.ModuleAssessment r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAssessmentService/SaveAssessment", ReplyAction="http://tempuri.org/IModuleAssessmentService/SaveAssessmentResponse")]
        System.Threading.Tasks.Task<int> SaveAssessmentAsync(StudentDataModel.ModuleAssessment r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAssessmentService/GetData", ReplyAction="http://tempuri.org/IModuleAssessmentService/GetDataResponse")]
        StudentDataModel.ModuleAssessment[] GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAssessmentService/GetData", ReplyAction="http://tempuri.org/IModuleAssessmentService/GetDataResponse")]
        System.Threading.Tasks.Task<StudentDataModel.ModuleAssessment[]> GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAssessmentService/GetAssesmentsByModule", ReplyAction="http://tempuri.org/IModuleAssessmentService/GetAssesmentsByModuleResponse")]
        StudentDataModel.ModuleAssessment[] GetAssesmentsByModule(StudentDataModel.CourseModule c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModuleAssessmentService/GetAssesmentsByModule", ReplyAction="http://tempuri.org/IModuleAssessmentService/GetAssesmentsByModuleResponse")]
        System.Threading.Tasks.Task<StudentDataModel.ModuleAssessment[]> GetAssesmentsByModuleAsync(StudentDataModel.CourseModule c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModuleAssessmentServiceChannel : StudentGradeManager.ModuleAssessmentServiceReference.IModuleAssessmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModuleAssessmentServiceClient : System.ServiceModel.ClientBase<StudentGradeManager.ModuleAssessmentServiceReference.IModuleAssessmentService>, StudentGradeManager.ModuleAssessmentServiceReference.IModuleAssessmentService {
        
        public ModuleAssessmentServiceClient() {
        }
        
        public ModuleAssessmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModuleAssessmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuleAssessmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModuleAssessmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveAssessment(StudentDataModel.ModuleAssessment r) {
            return base.Channel.SaveAssessment(r);
        }
        
        public System.Threading.Tasks.Task<int> SaveAssessmentAsync(StudentDataModel.ModuleAssessment r) {
            return base.Channel.SaveAssessmentAsync(r);
        }
        
        public StudentDataModel.ModuleAssessment[] GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<StudentDataModel.ModuleAssessment[]> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public StudentDataModel.ModuleAssessment[] GetAssesmentsByModule(StudentDataModel.CourseModule c) {
            return base.Channel.GetAssesmentsByModule(c);
        }
        
        public System.Threading.Tasks.Task<StudentDataModel.ModuleAssessment[]> GetAssesmentsByModuleAsync(StudentDataModel.CourseModule c) {
            return base.Channel.GetAssesmentsByModuleAsync(c);
        }
    }
}
