//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentGradeManager.StudentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/StudentGradeManagerService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentServiceReference.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/SaveStudent", ReplyAction="http://tempuri.org/IStudentService/SaveStudentResponse")]
        int SaveStudent(StudentDataModel.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/SaveStudent", ReplyAction="http://tempuri.org/IStudentService/SaveStudentResponse")]
        System.Threading.Tasks.Task<int> SaveStudentAsync(StudentDataModel.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/StudentLoginValidate", ReplyAction="http://tempuri.org/IStudentService/StudentLoginValidateResponse")]
        bool StudentLoginValidate(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/StudentLoginValidate", ReplyAction="http://tempuri.org/IStudentService/StudentLoginValidateResponse")]
        System.Threading.Tasks.Task<bool> StudentLoginValidateAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentById", ReplyAction="http://tempuri.org/IStudentService/GetStudentByIdResponse")]
        StudentDataModel.Student GetStudentById(System.Guid studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentById", ReplyAction="http://tempuri.org/IStudentService/GetStudentByIdResponse")]
        System.Threading.Tasks.Task<StudentDataModel.Student> GetStudentByIdAsync(System.Guid studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentEnrolledCourses", ReplyAction="http://tempuri.org/IStudentService/GetStudentEnrolledCoursesResponse")]
        StudentDataModel.Course[] GetStudentEnrolledCourses(System.Guid studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentEnrolledCourses", ReplyAction="http://tempuri.org/IStudentService/GetStudentEnrolledCoursesResponse")]
        System.Threading.Tasks.Task<StudentDataModel.Course[]> GetStudentEnrolledCoursesAsync(System.Guid studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IStudentService/GetDataUsingDataContractResponse")]
        StudentGradeManager.StudentServiceReference.CompositeType GetDataUsingDataContract(StudentGradeManager.StudentServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IStudentService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<StudentGradeManager.StudentServiceReference.CompositeType> GetDataUsingDataContractAsync(StudentGradeManager.StudentServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : StudentGradeManager.StudentServiceReference.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<StudentGradeManager.StudentServiceReference.IStudentService>, StudentGradeManager.StudentServiceReference.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveStudent(StudentDataModel.Student student) {
            return base.Channel.SaveStudent(student);
        }
        
        public System.Threading.Tasks.Task<int> SaveStudentAsync(StudentDataModel.Student student) {
            return base.Channel.SaveStudentAsync(student);
        }
        
        public bool StudentLoginValidate(string userName, string password) {
            return base.Channel.StudentLoginValidate(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> StudentLoginValidateAsync(string userName, string password) {
            return base.Channel.StudentLoginValidateAsync(userName, password);
        }
        
        public StudentDataModel.Student GetStudentById(System.Guid studentId) {
            return base.Channel.GetStudentById(studentId);
        }
        
        public System.Threading.Tasks.Task<StudentDataModel.Student> GetStudentByIdAsync(System.Guid studentId) {
            return base.Channel.GetStudentByIdAsync(studentId);
        }
        
        public StudentDataModel.Course[] GetStudentEnrolledCourses(System.Guid studentId) {
            return base.Channel.GetStudentEnrolledCourses(studentId);
        }
        
        public System.Threading.Tasks.Task<StudentDataModel.Course[]> GetStudentEnrolledCoursesAsync(System.Guid studentId) {
            return base.Channel.GetStudentEnrolledCoursesAsync(studentId);
        }
        
        public StudentGradeManager.StudentServiceReference.CompositeType GetDataUsingDataContract(StudentGradeManager.StudentServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<StudentGradeManager.StudentServiceReference.CompositeType> GetDataUsingDataContractAsync(StudentGradeManager.StudentServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
