//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentGradeManager.ResultServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResultServiceReference.IResultService")]
    public interface IResultService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultService/SaveResult", ReplyAction="http://tempuri.org/IResultService/SaveResultResponse")]
        int SaveResult(StudentDataModel.Result r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultService/SaveResult", ReplyAction="http://tempuri.org/IResultService/SaveResultResponse")]
        System.Threading.Tasks.Task<int> SaveResultAsync(StudentDataModel.Result r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultService/GetData", ReplyAction="http://tempuri.org/IResultService/GetDataResponse")]
        StudentDataModel.Result[] GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultService/GetData", ReplyAction="http://tempuri.org/IResultService/GetDataResponse")]
        System.Threading.Tasks.Task<StudentDataModel.Result[]> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResultServiceChannel : StudentGradeManager.ResultServiceReference.IResultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResultServiceClient : System.ServiceModel.ClientBase<StudentGradeManager.ResultServiceReference.IResultService>, StudentGradeManager.ResultServiceReference.IResultService {
        
        public ResultServiceClient() {
        }
        
        public ResultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveResult(StudentDataModel.Result r) {
            return base.Channel.SaveResult(r);
        }
        
        public System.Threading.Tasks.Task<int> SaveResultAsync(StudentDataModel.Result r) {
            return base.Channel.SaveResultAsync(r);
        }
        
        public StudentDataModel.Result[] GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<StudentDataModel.Result[]> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
